#165158
NaN-tic/trytond-sale_edi_ediversa pull request #6
Opened 2024-02-29 14:03 UTC by nan-tic-dev

2024-03-01 11:30 UTC, bernatnan requested changes
LGTM

2024-03-01 11:30 UTC, bernatnan commented on sale_edi.py
> -                                or edi_sale.sale.id)))
Is needed to remove the message and transactions.

2024-03-04 13:05 UTC, raimonesteve commented on sale_edi.py
> -                                or edi_sale.sale.id)))
d4c1e2f26e29de7263a6482d5417d01d78594d73

2024-03-08 12:07 UTC, bernatnan approved these changes
LGTM

2024-03-08 13:40 UTC, merged